allowBuilds:
  '@prisma/engines': true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - sharp
  - unrs-resolver
overrides:
  '@types/pg': 8.23.1
  deepmerge-ts: 8.0.2
